import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased relative overflow-x-hidden `}>
        <div className=" max-w-[1200px] m-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
