import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={` antialiased relative overflow-x-hidden
        `}
      >
        <SessionProvider>
          <div className=" max-w-[1200px] m-auto">
            <Header />
            {children}
            <Toaster />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
